import Head from "next/head";
import Dashboard from "@/pages/dashboard";
import SideMenu from "@/components/SideMenu";
import Header from "@/components/Header";
import styles from "@/styles/Home.module.css";
import { useSession } from "next-auth/react";
import Login from "@/components/Login";

export default function Home() {
  const { data: session } = useSession();
  const userProfileImg = session?.user?.image as string;
  const userName = session?.user?.name as string;
  return (
    <>
      <Head>
        <title>Data Dashboard</title>
        <meta name={"description"} content={"Generated by create next app"} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        {session && (
          <>
            <SideMenu />
            <Dashboard />
          </>
        )}
        <Login />
      </main>
    </>
  );
}
