import Head from "next/head";
import Dashboard from "@/pages/dashboard";
import SideMenu from "@/pages/components/SideMenu";
import Header from "@/pages/components/Header";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Data Dashboard</title>
        <meta name={"description"} content={"Generated by create next app"} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <SideMenu></SideMenu>
        <Dashboard />
      </main>
    </>
  );
}
